language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t serhatkayaa/ticket-ui -f Dockerfile.dev .

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: ticket-ui
    env: TicketUi-env
    bucket_name: elasticbeanstalk-us-east-1-566740074909
    bucket_path: ticket-ui
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY